Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110911-1-hg-git
extra : transplant_source : %D2%96%A4l%B3%ED%A1%BF%0BEe%97%B5y%D3%A8%28%AA%EE%9B