Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110901-5-hg-git
extra : transplant_source : u/%EE%8C%23%B7%07Z%03%23%01%D9%B9%9C%00%0A%B9%E4%CD%08