Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110901-4-hg-git
extra : transplant_source : %F6R%A6%CB%09%DC%05%28w%A8%FF%BB%C3%19%84%90%C8%E3%0F