Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110918-18-hg-git
extra : rebase_source : 99926f10dc80afe1e5bca7a30a9600c84d9f50a3