Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110914-3-hg-git
extra : transplant_source : u%BBM%07%85%0D%0Fb%A9%C7j%28%3F%7C%A3%60%EF%E6%CF%0F