Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110822-2-hg-git
extra : rebase_source : 69b200532b97d57f50cd87311cae8f0b71355355