Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110902-1-hg-git
extra : transplant_source : o%83%40%1F%0C%C1%17%0A1%CBH%F6%E3%C7v%FB%BBn%95%B5