Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110830-2-hg-git
extra : transplant_source : %11%A65%9FQf%B5h%B4%B6%00%D3%95%9E%EA%B5%A5%AFX%18