Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110828-1-hg-git
extra : transplant_source : %A6L%2CK%C6U%D1%93%AC%AE%F5%F4%D9x%A4%FC%CE%D2%3F%8D