Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110827-3-hg-git
extra : transplant_source : %8B%16%8E%A4%08%C7sM%95%F0%40%82%13%0F%F9%AA%E8z%86%7D